Workarround for the EGL crash in the current GPU driver
Without the resolution adjustment *any* sample program in /opt/fsl-gpu-sdk
stops with

ERROR: demo setup failed with: eglCreateWindowSurface(m_hDisplay, m_hConfig, hWi
ndow, nullptr) failed with error code 12291 at source/FslDemoHostEGL/EGLDemoHost
.cpp(504)

One entry in the NXP forum suggested to setting default_bpp to '16'.
And VPeter suggested to provide a resolution which is dividable by 8

http://www.udoo.org/forum/threads/lvds-and-egl-error-0x3003-cannot-get-surface.3531/#post-17127


Signed-off-by: Christian Ege <k4230r6@gmail.com>